### ISSUE TITLE
tm1_get_element need to return Attributes also

### ISSUE THREAD

**Issue by singla** [muhammedalionder/tm1r#6]
Currently tm1_get_element returns only name, unique name, index, level, type, components and it ignores attribute property completely. There is no way to get specific attribute (such as alias) for a dimension element. Please let me know, if this is not correct.

**Comment by muhammedalionder** [comment]
Hi, yes this is correct. tm1_get_element function does not return attributes and their values. I can add this feature as an enhancement in the next release.
Alternatively, you can get the attribute values from attribute cube with tm1_get_data function:
i.e `tm1_get_data(TM1ConnectionObject, "}ElementAttributes_DimensionName", "ElementName", "AttributeName")`

**Comment by singla** [comment]
Hello,
Yes thanks. When is the expected next release?
Also, can you please elaborate on tm1_get_data(TM1ConnectionObject, "}ElementAttributes_DimensionName", "ElementName", "AttributeName") - "ElementAttributes_DimensionName" - what is this input supposed to be? 

Thanks!

**Comment by muhammedalionder** [comment]
Next release will be at the end of this month hopefully.

For the example, let say you want to get "Description" attribute of "Total" element in "Account" dimension.
Then the function should be: `tm1_get_data(TM1ConnectionObject, "}ElementAttributes_Account", "Total", "Description")`

**Comment by singla** [comment]
Thank you. Looking forward to the release.

**Comment by muhammedalionder** [comment]
Version 1.1.5 including this enhancement is uploaded to cran. It will be soon available in cran in a couple of days.
Please check and log an issue in case of a problem.
