### ISSUE TITLE
Connect TM1 from local R studio

### ISSUE THREAD

**Issue by csuneelmba** [muhammedalionder/tm1r#7]
Can you please provide details steps to connect TM1 instances from my local machine via R studio
TM1 installed in windows server
R studio installed in my local machine
Could you please help me on this..

**Comment by muhammedalionder** [comment]
You need to get : 
- computer name or ip of windows server machine
- httpport number parameter of tm1 model (you can find this in tm1s.cfg file)
- and username and password for your account
If you can specify these parameters, I can help on the function

Then you need create a connection object with this function:
tm1_connection(adminhost = "localhost", httpport = "",
username = "admin", password = "apple",
namespace="", ssl=TRUE, base_url="")

after that, you can pass this object to any other tm1r function.

**Comment by csuneelmba** [comment]
Thank you
